### ISSUE TITLE
Search Issue on Relationship Field Component

### ISSUE THREAD

**Issue by sahasprajapati** [r1tsuu/payload-plugin-collections-docs-order#1]
Issue:

Payload V2 

"defaultSort" in CollectionConfig is used by the relationship components for querying the search parameter.

For a long list async react select this will cause issue as it will not fetch the desired search property.

![image](https://github.com/r1tsuu/payload-plugin-collections-docs-order/assets/19515458/8212c33e-7cc3-49de-92b5-532712771db5)

![image](https://github.com/r1tsuu/payload-plugin-collections-docs-order/assets/19515458/a1cba485-f2e0-4e20-b78c-273dc068e89a)

Solution:

I was able to overcome the issue by setting up "defaultSort": "preffered-columnName" in collection config.
Then using the admin->sortOptions to obtain the sort effect on relationship component.

![image](https://github.com/r1tsuu/payload-plugin-collections-docs-order/assets/19515458/0f3fe807-c1ff-4b0b-a8a6-36e973a57602)

**Comment by r1tsuu** [comment]
I moved an option to use`defaultSort` by `docOrder` field that added by the plugin for collections with enabled feature to plugin options and by default made it disabled. 
```ts
collectionsDocsOrderPlugin({
  collections: [{ slug: 'pages' }],  // The feature will be enabled only for collections that are in this array.,
  defaultSortByDocOrder: true, // Optional, if you want to use `docOrder` field for default sort in the selected collections, default - `false`
}),
```

Update to 0.0.18, should fix your problem.

**Comment by sahasprajapati** [comment]
Awesome. Works like a charm!!
